/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.salle.custommoodle.view;

import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import edu.salle.custommoodle.model.Materia;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luisd
 */
public class MateriaWindow extends javax.swing.JFrame {
    private static List<Materia> materiaList = new ArrayList<>();

    /**
     * Creates new form MateriaWindow
     */
    public MateriaWindow() {
        initComponents();
        this.setTitle("Materias");
        load();
        refresh(materiaList);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tMateria = new javax.swing.JTable();
        cbMateria = new javax.swing.JComboBox<>();
        tfDocente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        bAsignar = new javax.swing.JButton();
        bRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tMateria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Docente"
            }
        ));
        jScrollPane1.setViewportView(tMateria);

        cbMateria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Materia", "Matemáticas", "Computación", "Inglés" }));

        jLabel1.setText("Nombre del docente:");

        bAsignar.setText("Asignar docente");
        bAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAsignarActionPerformed(evt);
            }
        });

        bRegresar.setText("Regresar");
        bRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(cbMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(30, 30, 30))
                            .addComponent(tfDocente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(bAsignar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bRegresar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(bRegresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(bAsignar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void commitChanges(List<Materia> materiaList) throws IOException
    {
        try
        {
            Gson gson = new Gson();
            FileWriter fw = new FileWriter("materia.json");
            fw.write(gson.toJson(materiaList));
        }
        catch (Exception ex)
        {
            ex.printStackTrace();
        }
    }
    
    public void load ()
    {
        try
        {
            Gson gson = new Gson();
            BufferedReader br = new BufferedReader(new FileReader("materia.json"));
            materiaList = gson.fromJson(br, new TypeToken<List<Materia>>(){}.getType());
            if(materiaList==null)
            {
                materiaList = new ArrayList<>();
            }
        }
        catch (Exception ex)
        {
            ex.printStackTrace();
        }
    }
    
    private void bAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAsignarActionPerformed
        // TODO add your handling code here:
        Materia m = new Materia();
        m.setNombre(cbMateria.getSelectedItem().toString());
        m.setDocente(tfDocente.getText());
        actualizar(m);
        refresh(materiaList);
    }//GEN-LAST:event_bAsignarActionPerformed

    private void bRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegresarActionPerformed
        // TODO add your handling code here:
        MainWindow mw = new MainWindow();
        mw.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bRegresarActionPerformed

    public void actualizar(Materia student)
    {
        int pos = 9;
        if(student.getNombre().toLowerCase().equals("matemáticas"))
            pos=0;
        else if(student.getNombre().toLowerCase().equals("computación"))
            pos=1;
        else
            pos=2;
        materiaList.set(pos, student);
    }
    
    public void clear()
    {
        DefaultTableModel dtm = (DefaultTableModel)tMateria.getModel();
        while(dtm.getRowCount()>0)
            dtm.removeRow(0);
    }
    
    public void refresh(List<Materia> materiaList)
    {
        clear();
        DefaultTableModel dtm = (DefaultTableModel)tMateria.getModel();
        Object[] emptyRow = {""};
        
        for (int i = 0; i < materiaList.size() ; i++) {
            dtm.addRow(emptyRow);
            dtm.setValueAt(materiaList.get(i).getNombre(), i, 0); //Valor a insertar, , columna
            dtm.setValueAt(materiaList.get(i).getDocente(), i, 1);
        }
        
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAsignar;
    private javax.swing.JButton bRegresar;
    private javax.swing.JComboBox<String> cbMateria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tMateria;
    private javax.swing.JTextField tfDocente;
    // End of variables declaration//GEN-END:variables
}
